### ISSUE TITLE
Some question about code

### ISSUE THREAD

**Issue by Ayanami2019** [voidstrike/TDPNet#3]
Hello, I tried to run your code on my machine (windows, cuda11.0, pytorch1.2.0), but encountered some problems when compiling pytorch_structural_losses, as shown below, I hope you can take a moment to help I solve this problem,thanks.

****

(mywork) D:\projects\TDPNet-main\src\metrics\pytorch_structural_losses>make
CXX src/structural_loss.cpp
g++ src/structural_loss.cpp -MMD -MP -pthread -fPIC -fwrapv -std=c++11 -DNDEBUG -O3 -I./ -I/include -DTORCH_API_INCLUDE_EXTENSION_H -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wno-sign-compare -Wcomment -c -o objs/structural_loss.o
src/structural_loss.cpp:1:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
                                   ^
compilation terminated.
Makefile:83: recipe for target 'objs/structural_loss.o' failed
make: *** [objs/structural_loss.o] Error 1

![)VAJM(Y34TK@`NSM_UT9QF](https://user-images.githubusercontent.com/49433502/134764207-02a298c5-7024-45f7-8ab3-f99e883bdce1.png)

**Comment by voidstrike** [comment]
@Ayanami2019 Hello, unfortunately, we didn't implement this part and just borrow them from [here](https://github.com/stevenygd/PointFlow/blob/master/install.sh). I'm also not sure about the code's behavior in Windows. Maybe you can seek some help there? (Or as we suggested in the README, use Kaolin instead)

Literally, it says that "ATen/cuda/CUDAContext.h: No such file or directory". Could you please check your CUDA installation and find this file? BTW, this path works for Linux.

**Comment by Ayanami2019** [comment]
Thanks for your reply. I have now successfully run the code on ubuntu.
