### ISSUE TITLE
Error in generating view.

### ISSUE THREAD

**Issue by Ayanami2019** [voidstrike/TDPNet#4]
Sorry to bother you again. When I used the view_genetator.py to generate the view, an error occurred in this line. The reason should be that I don’t have the phong.py. Can you provide it? Thanks！

https://github.com/voidstrike/TDPNet/blob/b75a04a824421de9b4cc290f7222fe94b398fb78/src/view_generator.py#L80

**Comment by voidstrike** [comment]
@Ayanami2019 Hey, I have uploaded the phony.py, please have a look.

Please also check [here](https://github.com/WeiTang114/BlenderPhong) for reference. I'm not sure whether the version of Blender matters,

BTW, in case you are dealing with other datasets, please modify the "view_generator.py" accordingly. (L75 & L79 are hardcoded)

**Comment by Ayanami2019** [comment]
Thanks！
