### ISSUE TITLE
About dataset.

### ISSUE THREAD

**Issue by VIMLab-hfut** [voidstrike/TDPNet#5]
Hello, I am very sorry to trouble you again. But when I used view_generator.py to generate data, an error occurred:

![O %P)PA$T}H56Z5T)TY%)80](https://user-images.githubusercontent.com/72554304/135221220-4405761a-748e-4d33-b2ef-18345fb96541.png)
I tried many versions(2.93,2.79,2.74) of blender and finally failed to solve it. So I would like to ask you what should I do to solve it, or can you share the ShapeNet dataset you have processed?

**Comment by voidstrike** [comment]
@VIMLab-hfut Thanks for your interest!

It looks like you are running the code under a Win system. If applicable, could you please try to run the code in a Linux system? We didn't conduct any test in Windows. 

For the blender, I have 2.83.18 installed in my machine (Should be compatible with the current "phony.py"). This code [here](https://github.com/WeiTang114/BlenderPhong) should be compatible with 2.79 or some earlier versions. In addition, I'm not sure whether version >= 2.90 changes the function signatures.

I'm not sure about the license of ShapeNet. In case of any permit issue, please download the dataset and process it by yourself. Thanks.

**Comment by Ayanami2019** [comment]
Thank you for your answer, I will try to run the code using the Linux system these days

**Comment by Ayanami2019** [comment]
Hello, today I tried to use blender (v2.83, v2.79) to generate data again on ubuntu system, but it still got the same error (keyerror). I don't know how to solve this error. Is your original dataset downloaded from the ShapeNet official website? Is it the ShapeNetV1 or ShapeNetV2 version?

**Comment by Ayanami2019** [comment]
![error](https://user-images.githubusercontent.com/49433502/136939962-3a5e3540-1484-499d-a63d-9c4b2a5d5e79.png)

This is an error message. Do you know what caused it?

**Comment by voidstrike** [comment]
@Ayanami2019 Hey, please refer to the updated `phong.py` and sorry for the mistake.

2.83 was adopted in our later research and the ShapeNet images are generated via 2.79. I have double-checked the code and re-run the blender to make sure the code is working. (See attached screenshots)

L11 of 'phong.py' is hard-coded, so please modify the path based on your system (I also uploaded the background.jpg we used). 

I used ShapeNetCore.v2.

![Screen Shot 2021-10-12 at 2 50 09 PM](https://user-images.githubusercontent.com/7570396/137020468-08f919db-b426-4c1e-995b-9e951f9c6686.png)

![Screen Shot 2021-10-12 at 2 50 43 PM](https://user-images.githubusercontent.com/7570396/137020492-4a8455a3-1e78-4cce-9f69-4c377c0f501c.png)

**Comment by Ayanami2019** [comment]
@voidstrike Thank you, I updated phong.py according to your method, and I can now successfully generate views. But now I have encountered a new problem. All the generated images have only black and white pixels (0 and 255), as shown in the figure below. What should I do to generate a grayscale image?
![ZN_5E11P)EP0SMYH(B9~6 K](https://user-images.githubusercontent.com/49433502/137088512-844f21d7-8db2-4592-87f3-13e5ccba259d.png)
![OL183JNCIDMFLTT0 0T)NB0](https://user-images.githubusercontent.com/49433502/137088576-4ffa612a-2028-4bdb-8579-b71982e713e0.png)

**Comment by voidstrike** [comment]
@Ayanami2019 Hey, do you encounter this problem for all models? I tried the model presented in your last error msg and the results are correct.

INPUT:
<img width="1046" alt="Screen Shot 2021-10-13 at 11 01 59 AM" src="https://user-images.githubusercontent.com/7570396/137170962-c29a09d0-c7df-424b-86c6-00d7f519edca.png">

OUTPUT:
<img width="615" alt="Screen Shot 2021-10-13 at 11 03 40 AM" src="https://user-images.githubusercontent.com/7570396/137171076-afd7140e-951f-4107-9b6c-4bf8b16b54be.png">

Could you please try other models to see if the error persists? For example,
02691156/1a04e3eab45ca15dd86060f189eb133
02691156/1a9b552befd6306cc8f2d5fe7449af61
These two are well-colored

If you look into "phong.py", you will see that we just load the object, rotate the camera, and render it.

**Comment by Ayanami2019** [comment]
@voidstrike  Thank you for your answer, there is no problem now.

**Comment by Ayanami2019** [comment]
@voidstrike I'm sorry to trouble you again that I still have a problem that has not been resolved. What should I do to  generate point cloud? I don't know how to use the function named pc_sampling in view_generator.py. And what is the version of PCL you are using?

**Comment by voidstrike** [comment]
@Ayanami2019 I'm sorry but I didn't get your point. What do you mean by "generate point cloud"? The model will output a tensor with shape (Batch_size, 2048, 3), you just need to iterate through the tensor and save each of them.

**Comment by Ayanami2019** [comment]
@voidstrike  I'm sorry this is my mistake. What I mean is how to sample the models in the ShapeNet dataset to get the point cloud ground truth of each model.

**Comment by voidstrike** [comment]
@Ayanami2019 Oh, sorry about that one. I didn't preprocess the point cloud by myself. When I got the dataset, there is a "npy_file.npy" for each ShapeNet model (As you can see in the `mv_dataset.py`).
I asked my colleague but he also forget the data source. It looks like the npy files are from [here](https://github.com/stevenygd/PointFlow), or you may need to do the pcl_mesh_sampling and convert .pcd file to .npy.

**Comment by Ayanami2019** [comment]
@voidstrike Thanks!

**Comment by voidstrike** [comment]
Solved
